//! Opcodes for Bengal VM

/// Opcodes for Bengal VM
#[repr(u8)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Opcode {
    Nop = 0x00,
    LoadConst = 0x10,
    LoadInt = 0x11,
    LoadFloat = 0x12,
    LoadBool = 0x13,
    LoadNull = 0x14,
    Move = 0x20,
    LoadLocal = 0x21,
    StoreLocal = 0x22,
    GetProperty = 0x30,
    SetProperty = 0x31,
    Call = 0x40,
    CallNative = 0x41,
    Invoke = 0x42,
    Return = 0x43,
    CallAsync = 0x44,
    CallNativeAsync = 0x45,
    InvokeAsync = 0x46,
    Await = 0x47,
    Spawn = 0x48,
    InvokeInterface = 0x49,
    InvokeInterfaceAsync = 0x4A,
    CallNativeIndexed = 0x4B,
    CallNativeIndexedAsync = 0x4C,
    Jump = 0x50,
    JumpIfTrue = 0x51,
    JumpIfFalse = 0x52,
    Equal = 0x60,
    NotEqual = 0x61,
    And = 0x62,
    Or = 0x63,
    Not = 0x64,
    Concat = 0x65,
    Greater = 0x66,
    Less = 0x67,
    Add = 0x68,
    Subtract = 0x69,
    GreaterEqual = 0x6A,
    LessEqual = 0x6B,
    Multiply = 0x70,
    Divide = 0x71,
    Line = 0x73,
    Convert = 0x74,
    Modulo = 0x75,
    Array = 0x76,
    Index = 0x77,
    BitAnd = 0x78,
    BitOr = 0x79,
    BitXor = 0x7A,
    BitNot = 0x7B,
    ShiftLeft = 0x7C,
    ShiftRight = 0x7D,
    TryStart = 0x80,
    TryEnd = 0x81,
    Throw = 0x82,
    Breakpoint = 0x90,
    Halt = 0xFF,
}

impl From<u8> for Opcode {
    fn from(value: u8) -> Self {
        match value {
            0x00 => Opcode::Nop,
            0x10 => Opcode::LoadConst,
            0x11 => Opcode::LoadInt,
            0x12 => Opcode::LoadFloat,
            0x13 => Opcode::LoadBool,
            0x14 => Opcode::LoadNull,
            0x20 => Opcode::Move,
            0x21 => Opcode::LoadLocal,
            0x22 => Opcode::StoreLocal,
            0x30 => Opcode::GetProperty,
            0x31 => Opcode::SetProperty,
            0x40 => Opcode::Call,
            0x41 => Opcode::CallNative,
            0x42 => Opcode::Invoke,
            0x43 => Opcode::Return,
            0x44 => Opcode::CallAsync,
            0x45 => Opcode::CallNativeAsync,
            0x46 => Opcode::InvokeAsync,
            0x47 => Opcode::Await,
            0x48 => Opcode::Spawn,
            0x49 => Opcode::InvokeInterface,
            0x4A => Opcode::InvokeInterfaceAsync,
            0x4B => Opcode::CallNativeIndexed,
            0x4C => Opcode::CallNativeIndexedAsync,
            0x50 => Opcode::Jump,
            0x51 => Opcode::JumpIfTrue,
            0x52 => Opcode::JumpIfFalse,
            0x60 => Opcode::Equal,
            0x61 => Opcode::NotEqual,
            0x62 => Opcode::And,
            0x63 => Opcode::Or,
            0x64 => Opcode::Not,
            0x65 => Opcode::Concat,
            0x66 => Opcode::Greater,
            0x67 => Opcode::Less,
            0x68 => Opcode::Add,
            0x69 => Opcode::Subtract,
            0x6A => Opcode::GreaterEqual,
            0x6B => Opcode::LessEqual,
            0x70 => Opcode::Multiply,
            0x71 => Opcode::Divide,
            0x73 => Opcode::Line,
            0x74 => Opcode::Convert,
            0x75 => Opcode::Modulo,
            0x76 => Opcode::Array,
            0x77 => Opcode::Index,
            0x78 => Opcode::BitAnd,
            0x79 => Opcode::BitOr,
            0x7A => Opcode::BitXor,
            0x7B => Opcode::BitNot,
            0x7C => Opcode::ShiftLeft,
            0x7D => Opcode::ShiftRight,
            0x80 => Opcode::TryStart,
            0x81 => Opcode::TryEnd,
            0x82 => Opcode::Throw,
            0x90 => Opcode::Breakpoint,
            0xFF => Opcode::Halt,
            _ => Opcode::Nop,
        }
    }
}
